name: dcm
description: |
  DNS & CA Management Stack Template
version: 0.1.0-beta-rancher1
category: Applications
maintainer: "Kazuhito Yamazawa <yamazawa@supersoftware.co.jp>"
license: MIT
projectURL: https://github.com/kyamazawa/kutil-calalog
